/* Generated by c3ppc - C3++ to C compiler */
/* C3++ has no preprocessor -- includes from import */

#include <stdio.h>

/* Module: hello */

int main(void) {
    printf("Hello, World!\n");
    return 0;
}
