# Generated by c3ppc - C3++ to x86-64 assembler
# Target: x86-64 Linux, linked with libc via gcc
.section .text
.globl main

.globl main
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $16, %rsp
    leaq .LC1(%rip), %rdi
    xorl %eax, %eax
    callq printf@PLT
    movq $0, %rax
    leave
    ret
    movq $0, %rax
    leave
    ret

.section .rodata
    .LC1:
    .string "Hello, World!\n"
