"""
C3++ ASM Code Generator — Full x86-64 backend
==============================================
Generates x86-64 Linux assembly (AT&T/GAS syntax) from parsed C3++ source.

Supports:
  - Functions with parameters (System V AMD64 ABI)
  - Local variables on the stack
  - Integer arithmetic (+, -, *, /, %)
  - while loops with labels
  - if/else statements
  - printf with format strings and integer args
  - Function calls
  - Enums (as integer constants)
  - Return statements

Target: x86-64 Linux, linked with libc via gcc.
Assembly: gcc -o out out.s  (AT&T syntax, default GAS)
"""

from typing import Dict, List, Tuple
from dataclasses import dataclass, field


@dataclass
class AsmContext:
    """Accumulates assembly sections."""
    rodata: List[str] = field(default_factory=list)
    bss: List[str] = field(default_factory=list)
    text: List[str] = field(default_factory=list)
    _str_counter: int = 0
    _str_map: Dict[str, str] = field(default_factory=dict)

    def add_string(self, literal: str) -> str:
        """Add a string literal to .rodata, return its label."""
        if literal in self._str_map:
            return self._str_map[literal]
        self._str_counter += 1
        label = f".LC{self._str_counter}"
        self._str_map[literal] = label
        inner = literal[1:-1]  # strip surrounding quotes
        # Escape trailing backslashes so they don't eat the closing quote in GAS
        trailing_bs = len(inner) - len(inner.rstrip('\\'))
        if trailing_bs % 2 == 1:
            inner += '\\'
        self.rodata.append(f'{label}:\n    .string "{inner}"')
        return label


class AsmGenerator:
    """
    Full x86-64 code generator for C3++.

    Stack frame layout per function:
        [rbp-8]   first local
        [rbp-16]  second local
        ...
        [rbp-N]   last local

    Parameters are received in registers and saved to stack:
        %rdi -> [rbp-8],  %rsi -> [rbp-16],  etc.
    """

    PARAM_REGS = ['%rdi', '%rsi', '%rdx', '%rcx', '%r8', '%r9']

    def __init__(self):
        self.ctx = AsmContext()
        self._locals: Dict[str, int] = {}   # varname -> offset from rbp (negative)
        self._stack_used = 0                 # bytes used by locals
        self._label_ctr = 0
        # Control flow context stack: list of ('while', begin_label, end_label)
        #                             or  ('if', end_label)  or  ('ifelse', else_label, end_label)
        self._ctx_stack: List[Tuple] = []
        self._pending_else = False  # True when we just finished an if body and expect "else"

    def _lbl(self, prefix: str = ".L") -> str:
        self._label_ctr += 1
        return f"{prefix}{self._label_ctr}"

    def _emit(self, line: str):
        self.ctx.text.append(line)

    # ── Public API ────────────────────────────────────────────────────

    def generate(self, parsed: dict, source_code: str) -> str:
        self.ctx = AsmContext()
        self._locals = {}
        self._stack_used = 0
        self._label_ctr = 0
        self._ctx_stack = []

        # Pre-scan source for string literals
        self._collect_strings(source_code)

        # Collect constants and enums as integer values
        enums = self._parse_enums(source_code)
        enums.update(self._parse_constants(source_code))

        # Generate each function
        for fn in parsed.get('functions', []):
            self._gen_function(fn['code'], enums)

        if not parsed.get('functions'):
            self._gen_main_fallback()

        # Assemble output
        result = []
        result.append("# Generated by c3ppc - C3++ to x86-64 assembler")
        result.append("# Target: x86-64 Linux, linked with libc via gcc")
        result.append(".section .text")
        result.append(".globl main")
        result.append("")
        result.extend(self.ctx.text)

        if self.ctx.rodata:
            result.append(".section .rodata")
            for s in self.ctx.rodata:
                result.append(f"    {s}")
            result.append("")

        if self.ctx.bss:
            result.append(".section .bss")
            for b in self.ctx.bss:
                result.append(f"    {b}")

        return "\n".join(result)

    # ── Pre-scan ──────────────────────────────────────────────────────

    def _collect_strings(self, source: str):
        import re
        for m in re.finditer(r'"([^"\\]*(?:\\.[^"\\]*)*)"', source):
            self.ctx.add_string(m.group(0))

    def _parse_constants(self, source: str) -> Dict[str, int]:
        """Extract const NAME = value as name->int mappings."""
        import re
        constants = {}
        for m in re.finditer(r'const\s+(\w+)\s*=\s*(\d+)\s*;', source):
            constants[m.group(1)] = int(m.group(2))
        return constants

    def _parse_enums(self, source: str) -> Dict[str, int]:
        """Extract enum values as name->int mappings."""
        import re
        enums = {}
        for m in re.finditer(r'enum\s+\w+\s*\{([^}]+)\}', source, re.DOTALL):
            body = m.group(1)
            next_val = 0
            for v in body.split(','):
                v = v.strip()
                if not v: continue
                vm = re.match(r'(\w+)\s*=\s*(.+)', v)
                if vm:
                    name = vm.group(1)
                    val_str = vm.group(2).strip()
                    try:
                        next_val = int(val_str)
                    except ValueError:
                        # Might be a previous enum value
                        next_val = enums.get(val_str, 0)
                    enums[name] = next_val
                    next_val += 1
                else:
                    enums[v] = next_val
                    next_val += 1
        return enums

    # ── Function Generation ───────────────────────────────────────────

    def _gen_function(self, code: str, enums: Dict[str, int]):
        import re
        # Strip @require/@ensure annotations
        code = re.sub(r'\s*@\w+\([^)]*\)', '', code)
        m = re.match(r'fn\s+[\w*\[\]?<>]+\s+(\w+)\s*\(([^)]*)\)\s*\{(.*)\}', code, re.DOTALL)
        if not m:
            return

        fn_name = m.group(1)
        params_str = m.group(2).strip()
        body = m.group(3).strip()

        # Reset locals
        self._locals = {}
        self._stack_used = 0
        self._ctx_stack = []

        # Parse parameters
        params = []
        if params_str and params_str != 'void':
            for p in params_str.split(','):
                p = p.strip()
                parts = p.rsplit(None, 1)
                if len(parts) == 2:
                    pname = parts[1].split('[')[0].strip()
                    params.append(pname)

        # Pre-scan body for local variable declarations
        local_names = []
        for line in body.split('\n'):
            ls = line.strip()
            vm = re.match(r'(?:int|long|short|char|bool|string|float|double|uint|ulong|ushrt|ichar|void\*?|size_t)\s+(\w+)', ls)
            if vm:
                local_names.append(vm.group(1))

        # Calculate total slots: params + locals
        total_slots = len(params) + len(local_names)
        reserve = max(16, ((total_slots + 1) * 8 + 15) // 16 * 16)

        self._emit(f".globl {fn_name}")
        self._emit(f"{fn_name}:")

        # Prologue
        self._emit(f"    pushq %rbp")
        self._emit(f"    movq %rsp, %rbp")
        self._emit(f"    subq ${reserve}, %rsp")
        self._stack_used = reserve

        # Pre-assign offsets for params
        for i, pname in enumerate(params):
            if i < len(self.PARAM_REGS):
                self._locals[pname] = -(i + 1) * 8

        # Pre-assign offsets for locals
        base = len(params)
        for i, lname in enumerate(local_names):
            self._locals[lname] = -(base + i + 1) * 8

        # Save params from registers to stack
        for i, pname in enumerate(params):
            if i < len(self.PARAM_REGS):
                self._emit(f"    movq {self.PARAM_REGS[i]}, {self._locals[pname]}(%rbp)")

        # Generate body
        self._gen_body(body, enums)

        # If we haven't seen a return, emit default return 0
        self._emit(f"    movq $0, %rax")
        self._emit(f"    leave")
        self._emit(f"    ret")
        self._emit("")

    def _alloc_local(self, name: str) -> int:
        """Allocate a new local variable on the stack. Returns offset from %rbp."""
        # If already pre-assigned, just return the existing offset
        if name in self._locals:
            return self._locals[name]
        self._stack_used += 8
        if self._stack_used % 16 != 0:
            self._stack_used += 8
        offset = -self._stack_used
        self._locals[name] = offset
        return offset

    # ── Body / Statement Generation ───────────────────────────────────

    def _gen_body(self, body: str, enums: Dict[str, int]):
        """Generate assembly for a block of statements."""
        for line in body.split('\n'):
            line = line.strip()
            if not line or line.startswith('//'):
                continue
            self._gen_statement(line, enums)

    def _gen_statement(self, stmt: str, enums: Dict[str, int]):
        """Generate assembly for one statement."""
        import re

        # ── Handle } else { on one line (common C/C3++ formatting) ──
        if stmt.startswith('}') and 'else' in stmt:
            self._gen_statement('}', enums)
            # Strip the leading '}' and process the rest (else {...})
            rest = stmt[1:].strip()
            self._gen_statement(rest, enums)
            return

        # ── Resolve pending else: if previous } closed an if block
        #    and the next statement isn't else, emit the else label now.
        if self._pending_else and not (stmt.startswith('else') and '{' in stmt):
            self._pending_else = False
            if self._ctx_stack and self._ctx_stack[-1][0] == 'if':
                _, else_lbl, end_lbl = self._ctx_stack.pop()
                self._emit(f"{else_lbl}:")

        # ── While loop ──
        m = re.match(r'while\s*\(\s*(.+?)\s*\)\s*\{?', stmt)
        if m and stmt.strip().endswith('{'):
            cond = m.group(1).strip()
            begin_lbl = self._lbl(".Lwhile")
            body_lbl = self._lbl(".Lwhilebody")
            end_lbl = self._lbl(".Lendwhile")
            self._ctx_stack.append(('while', begin_lbl, end_lbl))
            self._emit(f"{begin_lbl}:")
            self._gen_condition(cond, body_lbl, end_lbl, enums)
            self._emit(f"{body_lbl}:")
            return

        # ── If statement ──
        m = re.match(r'if\s*\(\s*(.+?)\s*\)\s*\{?', stmt)
        if m and stmt.strip().endswith('{'):
            cond = m.group(1).strip()
            else_lbl = self._lbl(".Lelse")
            end_lbl = self._lbl(".Lendif")
            self._ctx_stack.append(('if', else_lbl, end_lbl))
            self._pending_else = False
            self._gen_condition(cond, None, else_lbl, enums)
            return

        # ── Else ──
        if stmt.startswith('else') and '{' in stmt:
            # The if context should still be on the stack (not popped by } yet)
            if self._ctx_stack and self._ctx_stack[-1][0] == 'if':
                _, else_lbl, end_lbl = self._ctx_stack[-1]
                self._pending_else = False
                self._emit(f"    jmp {end_lbl}")
                self._emit(f"{else_lbl}:")
                # Replace context to track we're now in the else branch
                self._ctx_stack[-1] = ('ifelse', end_lbl)
            return

        # ── Close brace ──
        if stmt == '}':
            if self._ctx_stack:
                ctx = self._ctx_stack[-1]
                if ctx[0] == 'while':
                    self._ctx_stack.pop()
                    _, begin_lbl, end_lbl = ctx
                    self._emit(f"    jmp {begin_lbl}")
                    self._emit(f"{end_lbl}:")
                elif ctx[0] == 'if':
                    # Don't pop yet — an else may follow.
                    # Mark pending so the next statement can finalize.
                    self._pending_else = True
                elif ctx[0] == 'ifelse':
                    self._ctx_stack.pop()
                    _, end_lbl = ctx
                    self._emit(f"{end_lbl}:")
            return

        # ── io::printn("text") -> printf("text\n") ──
        m = re.match(r'io::printn\s*\(\s*"([^"]*)"\s*\);', stmt)
        if m:
            self._gen_printf(m.group(1) + '\\n', None, enums)
            return

        # ── io::print("text") -> printf("text") ──
        m = re.match(r'io::print\s*\(\s*"([^"]*)"\s*\);', stmt)
        if m:
            self._gen_printf(m.group(1), None, enums)
            return

        # ── io::printfn("fmt", args) -> printf("fmt\n", args) ──
        m = re.match(r'io::printfn\s*\(\s*"([^"]*)"(?:\s*,\s*(.+))?\s*\);', stmt)
        if m:
            self._gen_printf(m.group(1) + '\\n', m.group(2), enums)
            return

        # ── printf (legacy C style) ──
        m = re.match(r'printf\s*\(\s*"([^"]*)"(?:\s*,\s*(.+))?\s*\);', stmt)
        if m:
            self._gen_printf(m.group(1), m.group(2), enums)
            return

        # ── return ──
        m = re.match(r'return\s+(.+);', stmt)
        if m:
            self._gen_expr(m.group(1).strip(), enums)
            self._emit(f"    leave")
            self._emit(f"    ret")
            return
        if stmt == 'return;':
            self._emit(f"    movq $0, %rax")
            self._emit(f"    leave")
            self._emit(f"    ret")
            return

        # ── Variable declaration with init ──
        m = re.match(r'(?:int|long|short|char|bool|string|float|double|uint|ulong|ushrt|ichar|void\*?|size_t)\s+(\w+)\s*=\s*(.+);', stmt)
        if m:
            vname = m.group(1)
            self._gen_expr(m.group(2).strip(), enums)
            off = self._alloc_local(vname)
            self._emit(f"    movq %rax, {off}(%rbp)")
            return

        # ── Variable declaration without init ──
        m = re.match(r'(?:int|long|short|char|bool|string|float|double|uint|ulong|ushrt|ichar|void\*?|size_t)\s+(\w+)\s*;', stmt)
        if m:
            vname = m.group(1)
            off = self._alloc_local(vname)
            self._emit(f"    movq $0, {off}(%rbp)")
            return

        # ── Increment: var++ or var-- ──
        m = re.match(r'(\w+)\+\+;', stmt)
        if m and m.group(1) in self._locals:
            off = self._locals[m.group(1)]
            self._emit(f"    incq {off}(%rbp)")
            return
        m = re.match(r'(\w+)--;', stmt)
        if m and m.group(1) in self._locals:
            off = self._locals[m.group(1)]
            self._emit(f"    decq {off}(%rbp)")
            return

        # ── Compound assignment: var += expr; var -= expr; etc. ──
        m = re.match(r'(\w+)\s*(\+=|\-=|\*=|\/=|\%=|&=|\|=|\^=)\s*(.+);', stmt)
        if m:
            vname = m.group(1); op = m.group(2); expr = m.group(3).strip()
            if vname in self._locals:
                off = self._locals[vname]
                self._gen_expr(expr, enums)
                self._emit(f"    movq %rax, %rcx")
                self._emit(f"    movq {off}(%rbp), %rax")
                aop = {'+=': 'addq', '-=': 'subq', '*=': 'imulq', '&=': 'andq', '|=': 'orq', '^=': 'xorq'}
                if op in aop:
                    self._emit(f"    {aop[op]} %rcx, %rax")
                elif op == '/=':
                    self._emit(f"    cqo"); self._emit(f"    idivq %rcx")
                elif op == '%=':
                    self._emit(f"    cqo"); self._emit(f"    idivq %rcx"); self._emit(f"    movq %rdx, %rax")
                self._emit(f"    movq %rax, {off}(%rbp)")
            return

        # ── Assignment ──
        m = re.match(r'(\w+)\s*=\s*(.+);', stmt)
        if m:
            vname = m.group(1)
            self._gen_expr(m.group(2).strip(), enums)
            if vname in self._locals:
                self._emit(f"    movq %rax, {self._locals[vname]}(%rbp)")
            return

        # ── Expression statement (function call, etc.) ──
        if stmt.endswith(';'):
            self._gen_expr(stmt.rstrip(';'), enums)

    # ── Condition (for while/if) ──────────────────────────────────────

    def _gen_condition(self, cond: str, body_lbl: str, exit_lbl: str, enums: Dict[str, int]):
        """Generate a conditional branch. If body_lbl is None, fall through to body."""
        import re

        m = re.match(r'(.+?)\s*(==|!=|<=|>=|<|>)\s*(.+)', cond)
        if m:
            left = m.group(1).strip()
            op = m.group(2)
            right = m.group(3).strip()
            self._gen_expr(left, enums)
            self._emit(f"    pushq %rax")
            self._gen_expr(right, enums)
            self._emit(f"    movq %rax, %rcx")
            self._emit(f"    popq %rax")
            self._emit(f"    cmpq %rcx, %rax")
            # Jump to exit if condition is FALSE (inverted)
            inv = {'==': 'jne', '!=': 'je', '<': 'jge', '>': 'jle', '<=': 'jg', '>=': 'jl'}
            self._emit(f"    {inv.get(op, 'jne')} {exit_lbl}")
        else:
            # Boolean expression
            self._gen_expr(cond, enums)
            self._emit(f"    testq %rax, %rax")
            self._emit(f"    je {exit_lbl}")

    # ── printf ─────────────────────────────────────────────────────────

    def _gen_printf(self, fmt: str, args_str: str, enums: Dict[str, int]):
        # Load all args first (they go into %rsi, %rdx, etc.), then format string into %rdi
        if args_str:
            args = self._split_args(args_str)
            # Args go into %rsi (1st), %rdx (2nd), %rcx (3rd), %r8 (4th), %r9 (5th)
            arg_regs = ['%rsi', '%rdx', '%rcx', '%r8', '%r9']
            for i, arg in enumerate(args):
                if i < len(arg_regs):
                    self._gen_expr(arg.strip(), enums)
                    self._emit(f"    movq %rax, {arg_regs[i]}")

        # Format string goes into %rdi (first arg)
        fmt_label = self.ctx.add_string(f'"{fmt}"')
        self._emit(f"    leaq {fmt_label}(%rip), %rdi")

        self._emit(f"    xorl %eax, %eax")
        self._emit(f"    callq printf@PLT")

    # ── Expression ─────────────────────────────────────────────────────

    def _gen_expr(self, expr: str, enums: Dict[str, int]):
        """Generate assembly for an expression. Result in %rax."""
        import re
        expr = expr.strip()

        # Empty
        if not expr:
            self._emit(f"    movq $0, %rax")
            return

        # Integer literal
        m = re.match(r'^(-?\d+)$', expr)
        if m:
            self._emit(f"    movq ${m.group(1)}, %rax")
            return

        # String literal
        m = re.match(r'^"(.*)"$', expr)
        if m:
            label = self.ctx.add_string(f'"{m.group(1)}"')
            self._emit(f"    leaq {label}(%rip), %rax")
            return

        # Enum constant or known integer
        if expr in enums:
            self._emit(f"    movq ${enums[expr]}, %rax")
            return

        # Variable
        if expr in self._locals:
            self._emit(f"    movq {self._locals[expr]}(%rbp), %rax")
            return

        # Null/0
        if expr == '0' or expr == 'null':
            self._emit(f"    movq $0, %rax")
            return
        if expr == '1':
            self._emit(f"    movq $1, %rax")
            return

        # sizeof(int) etc. -> 8 (simplified for x86-64)
        m = re.match(r'sizeof\s*\(\s*\w+\s*\)', expr)
        if m:
            self._emit(f"    movq $8, %rax")
            return

        # Parenthesized expression
        if expr.startswith('(') and expr.endswith(')'):
            inner = expr[1:-1].strip()
            # Check if it's a cast: (int)expr
            cm = re.match(r'\((\w+)\)\s*(.*)', inner)
            if cm:
                self._gen_expr(cm.group(2), enums)
                return
            self._gen_expr(inner, enums)
            return

        # Dereference: *expr
        if expr.startswith('*') and not expr.startswith('**'):
            inner = expr[1:].strip()
            if inner.startswith('(') and inner.endswith(')'):
                inner = inner[1:-1].strip()
            self._gen_expr(inner, enums)
            self._emit(f"    movq (%rax), %rax")
            return

        # Address-of: &expr
        if expr.startswith('&'):
            inner = expr[1:].strip()
            if inner in self._locals:
                self._emit(f"    leaq {self._locals[inner]}(%rbp), %rax")
                return
            self._gen_expr(inner, enums)
            return

        # Function call: name(args)
        m = re.match(r'^(\w+)\s*\(([^)]*)\)$', expr)
        if m:
            func_name = m.group(1)
            args_str = m.group(2).strip()
            if args_str:
                args = self._split_args(args_str)
                # Load args right-to-left into registers
                for i in range(len(args) - 1, -1, -1):
                    self._gen_expr(args[i].strip(), enums)
                    if i < 6:
                        self._emit(f"    movq %rax, {self.PARAM_REGS[i]}")
            self._emit(f"    callq {func_name}@PLT")
            return

        # Binary arithmetic (left op right)
        # Match from right to handle nested: a + b * c -> a + (b * c)
        m = self._split_binary(expr)
        if m:
            left, op, right = m
            self._gen_expr(left, enums)
            self._emit(f"    pushq %rax")
            self._gen_expr(right, enums)
            self._emit(f"    movq %rax, %rcx")
            self._emit(f"    popq %rax")
            if op == '+':
                self._emit(f"    addq %rcx, %rax")
            elif op == '-':
                self._emit(f"    subq %rcx, %rax")
            elif op == '*':
                self._emit(f"    imulq %rcx, %rax")
            elif op == '/':
                self._emit(f"    cqo")
                self._emit(f"    idivq %rcx")
            elif op == '%':
                self._emit(f"    cqo")
                self._emit(f"    idivq %rcx")
                self._emit(f"    movq %rdx, %rax")
            elif op == '&':
                self._emit(f"    andq %rcx, %rax")
            elif op == '|':
                self._emit(f"    orq %rcx, %rax")
            elif op == '^':
                self._emit(f"    xorq %rcx, %rax")
            elif op == '<<':
                self._emit(f"    salq %cl, %rax")
            elif op == '>>':
                self._emit(f"    sarq %cl, %rax")
            return

        # Comparison: a == b, a != b, etc. -> produces 0 or 1
        m = re.match(r'(.+?)\s*(==|!=|<=|>=|<|>)\s*(.+)', expr)
        if m:
            left = m.group(1).strip()
            op = m.group(2)
            right = m.group(3).strip()
            self._gen_expr(left, enums)
            self._emit(f"    pushq %rax")
            self._gen_expr(right, enums)
            self._emit(f"    movq %rax, %rcx")
            self._emit(f"    popq %rax")
            self._emit(f"    cmpq %rcx, %rax")
            # SETcc instruction
            setcc = {'==': 'sete', '!=': 'setne', '<': 'setl', '>': 'setg',
                      '<=': 'setle', '>=': 'setge'}
            self._emit(f"    {setcc.get(op, 'sete')} %al")
            self._emit(f"    movzbq %al, %rax")
            return

        # Negation: -expr
        if expr.startswith('-') and not expr.startswith('--'):
            self._gen_expr(expr[1:], enums)
            self._emit(f"    negq %rax")
            return

        # Logical NOT: !expr
        if expr.startswith('!') and not expr.startswith('!='):
            self._gen_expr(expr[1:], enums)
            self._emit(f"    testq %rax, %rax")
            self._emit(f"    sete %al")
            self._emit(f"    movzbq %al, %rax")
            return

        # Fallback: try as variable name
        self._emit(f"    movq $0, %rax  # unsupported expr: {expr}")

    def _split_binary(self, expr: str):
        """Split binary expression at the outermost operator (right-to-left for left-assoc)."""
        import re
        # Operators in precedence order (lowest first)
        ops = [
            (r'\|\|', '||'),
            (r'&&', '&&'),
            (r'\|(?!\|)', '|'),
            (r'\^(?!\^)', '^'),
            (r'&(?!&)', '&'),
            (r'==|!=', '=='),
            (r'<=|>=|<|>', '<'),
            (r'<<|>>', '<<'),
            (r'\+|-', '+'),
            (r'\*|/|%', '*'),
        ]

        depth = 0
        in_str = False
        for op_pattern, op_name in ops:
            # Scan right to left for left-associativity
            i = len(expr) - 1
            while i >= 0:
                ch = expr[i]
                if ch == '"': in_str = not in_str; i -= 1; continue
                if in_str: i -= 1; continue
                if ch == ')': depth += 1; i -= 1; continue
                if ch == '(': depth -= 1; i -= 1; continue
                if depth != 0: i -= 1; continue

                # Try matching operator at position i
                for op_re, op_n in [(op_pattern, op_name)]:
                    m = re.match(op_re, expr[i:])
                    if m and m.start() == 0:
                        op_len = m.end()
                        left = expr[:i].strip()
                        right = expr[i + op_len:].strip()
                        if left and right:
                            return (left, op_n, right)
                i -= 1
        return None

    # ── Helpers ────────────────────────────────────────────────────────

    def _split_args(self, args_str: str) -> List[str]:
        args = []
        depth = 0
        current = []
        for ch in args_str:
            if ch == '(': depth += 1
            elif ch == ')': depth -= 1
            elif ch == ',' and depth == 0:
                args.append(''.join(current).strip())
                current = []
                continue
            current.append(ch)
        if current:
            args.append(''.join(current).strip())
        return args

    def _gen_main_fallback(self):
        self._emit(".globl main")
        self._emit("main:")
        self._emit("    pushq %rbp")
        self._emit("    movq %rsp, %rbp")
        label = self.ctx.add_string('"Hello from C3++!\\n"')
        self._emit(f"    leaq {label}(%rip), %rdi")
        self._emit(f"    callq printf@PLT")
        self._emit(f"    xorl %eax, %eax")
        self._emit(f"    leave")
        self._emit(f"    ret")
