"""
C3++ Code Generator
===================
Code generation for the C3++ programming language.
Generates C code from C3++ AST.
"""

from typing import List, Optional, Dict, Any
from c3ppc.ast_nodes.nodes import (
    ProgramAST, ModuleDeclAST, ImportDeclAST,
    BinaryExprAST, UnaryExprAST, AssignmentExprAST,
    CallExprAST, MemberExprAST, IndexExprAST,
    NewExprAST, ThisExprAST, SuperExprAST,
    IdentifierExprAST, LiteralAST,
    BlockAST, IfStatementAST, WhileStatementAST,
    ForStatementAST, ForeachStatementAST,
    SwitchStatementAST, CaseClauseAST,
    ReturnStatementAST, BreakStatementAST,
    ContinueStatementAST, DeferStatementAST,
    ExpressionStatementAST,
    VarDeclAST, FnDeclAST, FnParamAST,
    BasicTypeAST, PointerTypeAST, ArrayTypeAST,
    SliceTypeAST, FunctionTypeAST,
    ClassDeclAST, ClassBodyAST,
    ConstructorDeclAST, DestructorDeclAST,
    StructDeclAST, StructBodyAST,
    EnumDeclAST, EnumMemberAST,
    InterfaceDeclAST, InterfaceBodyAST,
    BaseAST
)


class CodeGenerator:
    """
    Code generator for C3++ programs.
    
    Generates C code from C3++ AST.
    """
    
    def __init__(self):
        self._output: List[str] = []
        self._indent_level: int = 0
        self._class_names: Dict[str, str] = {}  # C3++ class name -> C struct name
        self._vtable_count: int = 0
    
    def generate(self, program: ProgramAST) -> str:
        """
        Generate C code from a C3++ program.
        
        Args:
            program: Root AST node of the program
            
        Returns:
            Generated C code as string
        """
        self._output = []
        self._indent_level = 0
        
        # Generate header
        self._emit("/* Generated by c3ppc - C3++ to C compiler */")
        self._emit("#include <stdio.h>")
        self._emit("#include <stdlib.h>")
        self._emit("#include <string.h>")
        self._emit("")
        
        # Generate forward declarations
        self._generate_forward_declarations(program)
        
        # Generate includes
        for import_decl in program.imports:
            self._generate_import(import_decl)
        
        # Generate declarations
        for decl in program.declarations:
            self._generate_declaration(decl)
        
        return "\n".join(self._output)
    
    def _emit(self, line: str):
        """Emit a line of code with proper indentation."""
        indent = "    " * self._indent_level
        self._output.append(f"{indent}{line}")
    
    def _emit_raw(self, text: str):
        """Emit raw text without indentation."""
        self._output.append(text)
    
    def _generate_forward_declarations(self, program: ProgramAST):
        """Generate forward declarations for classes and functions."""
        for decl in program.declarations:
            if isinstance(decl, ClassDeclAST):
                self._emit(f"struct {decl.name};")
            elif isinstance(decl, StructDeclAST):
                self._emit(f"struct {decl.name};")
            elif isinstance(decl, FnDeclAST):
                ret_type = self._get_c_type(decl.return_type)
                params = ", ".join(["void"] if not decl.params else 
                                 [f"{self._get_c_type(p.type_annotation)} {p.name}" 
                                  for p in decl.params])
                self._emit(f"{ret_type} {decl.name}({params});")
        self._emit("")
    
    def _generate_import(self, node: ImportDeclAST):
        """Generate import (include in C)."""
        self._emit(f"#include \"{node.module_path}.h\"")
    
    def _generate_declaration(self, node: BaseAST):
        """Generate code for a declaration."""
        if isinstance(node, VarDeclAST):
            self._generate_var_decl(node)
        elif isinstance(node, FnDeclAST):
            self._generate_fn_decl(node)
        elif isinstance(node, ClassDeclAST):
            self._generate_class_decl(node)
        elif isinstance(node, StructDeclAST):
            self._generate_struct_decl(node)
        elif isinstance(node, EnumDeclAST):
            self._generate_enum_decl(node)
        elif isinstance(node, InterfaceDeclAST):
            self._generate_interface_decl(node)
    
    def _generate_var_decl(self, node: VarDeclAST):
        """Generate variable declaration."""
        type_name = self._get_c_type(node.type_annotation)
        if node.is_const:
            self._emit(f"const {type_name} {node.name}", )
            if node.initializer:
                self._emit_raw(f" = ")
                self._generate_expression(node.initializer)
            self._emit_raw(";")
        else:
            self._emit(f"{type_name} {node.name}")
            if node.initializer:
                self._emit_raw(f" = ")
                self._generate_expression(node.initializer)
            self._emit_raw(";")
    
    def _generate_fn_decl(self, node: FnDeclAST):
        """Generate function declaration."""
        ret_type = self._get_c_type(node.return_type)
        
        # Generate parameters
        params = []
        for param in node.params:
            param_type = self._get_c_type(param.type_annotation)
            params.append(f"{param_type} {param.name}")
        
        param_str = ", ".join(params) if params else "void"
        
        # Generate function header
        self._emit(f"{ret_type} {node.name}({param_str})")
        
        # Generate body
        if node.body:
            self._generate_statement(node.body)
        else:
            self._emit(";")
        self._emit("")
    
    def _generate_class_decl(self, node: ClassDeclAST):
        """Generate class declaration as C struct."""
        struct_name = node.name
        self._class_names[node.name] = struct_name
        
        # Generate struct
        self._emit(f"/* Class {node.name} */")
        self._emit(f"struct {struct_name} {{")
        self._indent_level += 1
        
        # Add vtable pointer if has virtual methods
        has_virtual = any(isinstance(m, FnDeclAST) and m.is_virtual 
                         for m in node.body.members if isinstance(m, FnDeclAST))
        if has_virtual:
            self._emit(f"void* _vtable;")
        
        # Generate member variables
        for member in node.body.members:
            if isinstance(member, VarDeclAST):
                type_name = self._get_c_type(member.type_annotation)
                self._emit(f"{type_name} {member.name};")
        
        self._indent_level -= 1
        self._emit(f"}};")
        self._emit("")
        
        # Generate methods as standalone functions
        for member in node.body.members:
            if isinstance(member, FnDeclAST):
                self._generate_method(node.name, member)
            elif isinstance(member, ConstructorDeclAST):
                self._generate_constructor(node.name, member)
            elif isinstance(member, DestructorDeclAST):
                self._generate_destructor(node.name, member)
    
    def _generate_method(self, class_name: str, node: FnDeclAST):
        """Generate method as standalone function."""
        ret_type = self._get_c_type(node.return_type)
        
        # Method name: ClassName_methodName
        method_name = f"{class_name}_{node.name}"
        
        # Generate parameters (first param is self)
        params = [f"struct {class_name}* self"]
        for param in node.params:
            param_type = self._get_c_type(param.type_annotation)
            params.append(f"{param_type} {param.name}")
        
        param_str = ", ".join(params)
        
        # Generate function
        self._emit(f"{ret_type} {method_name}({param_str})")
        
        if node.body:
            self._generate_statement(node.body)
        else:
            self._emit(";")
        self._emit("")
    
    def _generate_constructor(self, class_name: str, node: ConstructorDeclAST):
        """Generate constructor."""
        # Constructor returns void and takes self + params
        params = [f"struct {class_name}* self"]
        for param in node.params:
            param_type = self._get_c_type(param.type_annotation)
            params.append(f"{param_type} {param.name}")
        
        param_str = ", ".join(params)
        
        self._emit(f"void {class_name}_constructor({param_str})")
        self._generate_statement(node.body)
        self._emit("")
    
    def _generate_destructor(self, class_name: str, node: DestructorDeclAST):
        """Generate destructor."""
        self._emit(f"void {class_name}_destructor(struct {class_name}* self)")
        self._generate_statement(node.body)
        self._emit("")
    
    def _generate_struct_decl(self, node: StructDeclAST):
        """Generate struct declaration."""
        self._emit(f"struct {node.name} {{")
        self._indent_level += 1
        
        for member in node.body.members:
            type_name = self._get_c_type(member.type_annotation)
            self._emit(f"{type_name} {member.name};")
        
        self._indent_level -= 1
        self._emit(f"}};")
        self._emit("")
    
    def _generate_enum_decl(self, node: EnumDeclAST):
        """Generate enum declaration."""
        self._emit(f"enum {node.name} {{")
        self._indent_level += 1
        
        members = []
        for member in node.members:
            if member.value:
                members.append(f"{member.name} = {self._get_literal_value(member.value)}")
            else:
                members.append(member.name)
        
        self._emit(",\n".join(members))
        
        self._indent_level -= 1
        self._emit(f"}};")
        self._emit("")
    
    def _generate_interface_decl(self, node: InterfaceDeclAST):
        """Generate interface as function pointer struct."""
        self._emit(f"/* Interface {node.name} */")
        self._emit(f"struct {node.name}_vtable {{")
        self._indent_level += 1
        
        for member in node.body.members:
            if isinstance(member, FnDeclAST):
                ret_type = self._get_c_type(member.return_type)
                params = []
                for param in member.params:
                    param_type = self._get_c_type(param.type_annotation)
                    params.append(f"{param_type} {param.name}")
                param_str = ", ".join(params) if params else "void"
                self._emit(f"{ret_type} (*{member.name})({param_str});")
        
        self._indent_level -= 1
        self._emit(f"}};")
        self._emit("")
    
    def _generate_statement(self, node: BaseAST):
        """Generate code for a statement."""
        if isinstance(node, BlockAST):
            self._generate_block(node)
        elif isinstance(node, IfStatementAST):
            self._generate_if_statement(node)
        elif isinstance(node, WhileStatementAST):
            self._generate_while_statement(node)
        elif isinstance(node, ForStatementAST):
            self._generate_for_statement(node)
        elif isinstance(node, ForeachStatementAST):
            self._generate_foreach_statement(node)
        elif isinstance(node, SwitchStatementAST):
            self._generate_switch_statement(node)
        elif isinstance(node, ReturnStatementAST):
            self._generate_return_statement(node)
        elif isinstance(node, BreakStatementAST):
            self._emit("break;")
        elif isinstance(node, ContinueStatementAST):
            self._emit("continue;")
        elif isinstance(node, DeferStatementAST):
            # Defer is implemented with goto and labels in C
            self._emit(f"/* defer: */")
            self._generate_statement(node.statement)
        elif isinstance(node, ExpressionStatementAST):
            self._generate_expression(node.expression)
            self._emit_raw(";")
        elif isinstance(node, VarDeclAST):
            self._generate_var_decl(node)
        elif isinstance(node, FnDeclAST):
            self._generate_fn_decl(node)
    
    def _generate_block(self, node: BlockAST):
        """Generate block statement."""
        self._emit("{")
        self._indent_level += 1
        
        for stmt in node.statements:
            self._generate_statement(stmt)
        
        self._indent_level -= 1
        self._emit("}")
    
    def _generate_if_statement(self, node: IfStatementAST):
        """Generate if statement."""
        self._emit_raw("if (")
        self._generate_expression(node.condition)
        self._emit_raw(")")
        self._generate_statement(node.then_block)
        
        if node.else_block:
            self._emit_raw("else ")
            self._generate_statement(node.else_block)
    
    def _generate_while_statement(self, node: WhileStatementAST):
        """Generate while statement."""
        self._emit_raw("while (")
        self._generate_expression(node.condition)
        self._emit_raw(")")
        self._generate_statement(node.body)
    
    def _generate_for_statement(self, node: ForStatementAST):
        """Generate for statement."""
        self._emit_raw("for (")
        
        if node.init:
            self._generate_expression(node.init)
        self._emit_raw("; ")
        
        if node.condition:
            self._generate_expression(node.condition)
        self._emit_raw("; ")
        
        if node.update:
            self._generate_expression(node.update)
        
        self._emit_raw(")")
        self._generate_statement(node.body)
    
    def _generate_foreach_statement(self, node: ForeachStatementAST):
        """Generate foreach as for loop (simplified)."""
        # Simplified: just generate a comment and the loop body
        self._emit(f"/* foreach {node.variable} in ... */")
        self._emit_raw("for (int _i = 0; _i < _len; _i++)")
        self._emit("{")
        self._indent_level += 1
        self._emit(f"auto {node.variable} = _arr[_i];")
        self._generate_statement(node.body)
        self._indent_level -= 1
        self._emit("}")
    
    def _generate_switch_statement(self, node: SwitchStatementAST):
        """Generate switch statement."""
        self._emit_raw("switch (")
        self._generate_expression(node.expression)
        self._emit_raw(") {")
        self._indent_level += 1
        
        for case in node.cases:
            self._emit_raw("case ")
            self._generate_expression(case.value)
            self._emit_raw(":")
            self._indent_level += 1
            for stmt in case.statements:
                self._generate_statement(stmt)
            self._emit("break;")
            self._indent_level -= 1
        
        if node.default:
            self._emit("default:")
            self._indent_level += 1
            for stmt in node.default:
                if isinstance(stmt, BaseAST):
                    self._generate_statement(stmt)
            self._emit("break;")
            self._indent_level -= 1
        
        self._indent_level -= 1
        self._emit("}")
    
    def _generate_return_statement(self, node: ReturnStatementAST):
        """Generate return statement."""
        if node.value:
            self._emit_raw("return ")
            self._generate_expression(node.value)
            self._emit_raw(";")
        else:
            self._emit("return;")
    
    def _generate_expression(self, node: BaseAST):
        """Generate code for an expression."""
        if isinstance(node, LiteralAST):
            self._emit_raw(self._get_literal_value(node))
        elif isinstance(node, IdentifierExprAST):
            self._emit_raw(node.name)
        elif isinstance(node, BinaryExprAST):
            self._generate_expression(node.left)
            self._emit_raw(f" {node.operator} ")
            self._generate_expression(node.right)
        elif isinstance(node, UnaryExprAST):
            if node.is_prefix:
                self._emit_raw(f"{node.operator}")
                self._generate_expression(node.operand)
            else:
                self._generate_expression(node.operand)
                self._emit_raw(node.operator)
        elif isinstance(node, AssignmentExprAST):
            self._generate_expression(node.target)
            self._emit_raw(f" {node.operator} ")
            self._generate_expression(node.value)
        elif isinstance(node, CallExprAST):
            self._generate_expression(node.callee)
            self._emit_raw("(")
            args = []
            for arg in node.arguments:
                # Capture the generated text
                old_len = len(self._output)
                self._generate_expression(arg)
                if len(self._output) > old_len:
                    args.append(self._output[-1][4:] if self._output[-1].startswith("    ") else self._output[-1])
            self._emit_raw(", ".join(args))
            self._emit_raw(")")
        elif isinstance(node, MemberExprAST):
            self._generate_expression(node.object)
            self._emit_raw(f"->" if "self" in str(node.object) else ".{node.member}")
        elif isinstance(node, IndexExprAST):
            self._generate_expression(node.object)
            self._emit_raw("[")
            self._generate_expression(node.index)
            self._emit_raw("]")
        elif isinstance(node, NewExprAST):
            # Generate malloc + constructor call
            self._emit_raw(f"(struct {node.class_name}*)malloc(sizeof(struct {node.class_name}))")
        elif isinstance(node, ThisExprAST):
            self._emit_raw("self")
        elif isinstance(node, SuperExprAST):
            self._emit_raw("self->_parent")
    
    def _get_c_type(self, type_node: Optional[BaseAST]) -> str:
        """Convert C3++ type to C type."""
        if type_node is None:
            return "void"
        
        if isinstance(type_node, BasicTypeAST):
            type_map = {
                'int': 'int',
                'long': 'long',
                'short': 'short',
                'float': 'float',
                'double': 'double',
                'char': 'char',
                'bool': 'int',  # C doesn't have bool, use int
                'void': 'void',
                'string': 'char*'
            }
            return type_map.get(type_node.name, type_node.name)
        elif isinstance(type_node, PointerTypeAST):
            base = self._get_c_type(type_node.base_type)
            return f"{base}*"
        elif isinstance(type_node, ArrayTypeAST):
            base = self._get_c_type(type_node.element_type)
            return f"{base}*"
        elif isinstance(type_node, SliceTypeAST):
            base = self._get_c_type(type_node.element_type)
            return f"{base}*"
        elif isinstance(type_node, FunctionTypeAST):
            # Function pointers
            ret_type = self._get_c_type(type_node.return_type)
            return f"{ret_type}(*)()"
        
        return "void"
    
    def _get_literal_value(self, node: BaseAST) -> str:
        """Get literal value as C code."""
        if isinstance(node, LiteralAST):
            if node.literal_type == 'string':
                return f'"{node.value}"'
            elif node.literal_type == 'char':
                return f"'{node.value}'"
            elif node.literal_type == 'bool':
                return "1" if node.value else "0"
            else:
                return str(node.value)
        return ""


def generate_c_code(program: ProgramAST) -> str:
    """
    Generate C code from a C3++ program.
    
    Args:
        program: Root AST node of the program
        
    Returns:
        Generated C code as string
    """
    generator = CodeGenerator()
    return generator.generate(program)
