"""
C3++ Compiler (c3ppc)
====================
C3++ to x86-64 assembly compiler.

C3++ has no preprocessor -- modules are imported, constants use ALL_CAPS const.
Generates x86-64 assembly, assembled with: gcc -o out out.s
"""

import sys
import os
import re
from typing import List, Optional
from dataclasses import dataclass


@dataclass
class CompilerOptions:
    input_file: Optional[str] = None
    output_file: Optional[str] = None
    verbose: bool = False
    check_only: bool = False
    emit_c: bool = False


def _count_braces(line_text: str) -> int:
    depth = 0; j = 0
    in_str = in_char = in_lc = in_bc = False
    while j < len(line_text):
        ch = line_text[j]
        if in_bc:
            if ch == '*' and j + 1 < len(line_text) and line_text[j+1] == '/':
                in_bc = False; j += 2; continue
            j += 1; continue
        if in_lc: j += 1; continue
        if in_str:
            if ch == '\\' and j + 1 < len(line_text): j += 2; continue
            if ch == '"': in_str = False
            j += 1; continue
        if in_char:
            if ch == '\\' and j + 1 < len(line_text): j += 2; continue
            if ch == "'": in_char = False
            j += 1; continue
        if ch == '"': in_str = True
        elif ch == "'": in_char = True
        elif ch == '/' and j + 1 < len(line_text) and line_text[j+1] == '/':
            in_lc = True; j += 2; continue
        elif ch == '/' and j + 1 < len(line_text) and line_text[j+1] == '*':
            in_bc = True; j += 2; continue
        elif ch == '{': depth += 1
        elif ch == '}': depth -= 1
        j += 1
    return depth


class C3ppCompiler:
    """C3++ compiler: C3++ -> x86-64 assembly."""

    IMPORT_TO_HEADER = {
        'stdio': 'stdio.h', 'stdlib': 'stdlib.h', 'string': 'string.h',
        'math': 'math.h', 'ctype': 'ctype.h', 'time': 'time.h',
        'stdint': 'stdint.h', 'assert': 'assert.h',
        'std::io': 'stdio.h', 'std::lib': 'stdlib.h', 'std::string': 'string.h',
        'std::math': 'math.h', 'std::ctype': 'ctype.h', 'std::time': 'time.h',
        'std::stdint': 'stdint.h', 'std::assert': 'assert.h',
    }

    def __init__(self, options: Optional[CompilerOptions] = None):
        self._options = options or CompilerOptions()
        self._lexer = None

    def compile(self, source_code: str) -> str:
        if self._options.emit_c:
            return self._compile_to_c(source_code)
        tokens = self._tokenize(source_code)
        parsed = self._parse_source(source_code, tokens)
        from c3ppc.codegen.asmgen import AsmGenerator
        return AsmGenerator().generate(parsed, source_code)

    def _compile_to_c(self, source_code: str) -> str:
        """Generate C code from C3++ source (line-by-line transpilation)."""
        lines = source_code.split('\n')
        out = []
        out.append("/* Generated by c3ppc - C3++ to C compiler */")
        out.append("")
        for line in lines:
            s = line.strip()
            if not s or s.startswith('//'):
                continue
            out.append(self._transpile_line(s))
        return '\n'.join(out) + '\n'

    def _transpile_line(self, s: str) -> str:
        """Transpile one C3++ line to C."""
        # import std::io -> #include <stdio.h>
        if s.startswith('import '):
            p = s[7:].rstrip(';').strip()
            mapping = {
                'std::io': 'stdio.h', 'std::lib': 'stdlib.h',
                'std::string': 'string.h', 'std::math': 'math.h',
                'stdio': 'stdio.h', 'stdlib': 'stdlib.h',
                'string': 'string.h', 'math': 'math.h',
            }
            header = mapping.get(p, f'{p}.h')
            return f'#include <{header}>'

        # module -> comment
        if s.startswith('module '):
            return f'/* {s} */'

        # const NAME = VALUE; -> #define NAME VALUE
        if s.startswith('const '):
            p = s[6:].rstrip(';').strip()
            eq = p.find('=')
            if eq >= 0:
                name = p[:eq].strip()
                val = p[eq+1:].strip()
                return f'#define {name} {val}'
            return f'/* {s} */'

        # fn TYPE NAME(...) { -> TYPE NAME(...) {
        if s.startswith('fn '):
            rest = s[3:]  # strip 'fn '
            # fn void main() -> int main()
            if rest.startswith('void main'):
                rest = 'int main' + rest[9:]
            # Generic: strip fn, convert types
            result = ''
            i = 0
            while i < len(rest):
                if rest[i:].startswith('string[]'):
                    result += 'char**'; i += 8
                elif rest[i:].startswith('string'):
                    result += 'char*'; i += 6
                elif rest[i:].startswith('bool'):
                    result += 'int'; i += 4
                else:
                    result += rest[i]; i += 1
            return result

        # io::printn("text") -> printf("text\n")
        if s.startswith('io::printn("'):
            inner = s[11:s.rfind('"')]
            return f'    printf("{inner}\\n");'

        # io::print("text") -> printf("text")
        if s.startswith('io::print("'):
            inner = s[10:s.rfind('"')]
            return f'    printf("{inner}");'

        # io::printfn("fmt", args) -> printf("fmt\n", args)
        if s.startswith('io::printfn("'):
            # Find the closing quote of the format string
            rest_after_io = s[12:]  # after io::printfn(
            # Find the first unescaped quote
            i = 1  # skip opening quote
            while i < len(rest_after_io):
                if rest_after_io[i] == '\\':
                    i += 2; continue
                if rest_after_io[i] == '"': break
                i += 1
            fmt = rest_after_io[1:i]  # format string without quotes
            args_part = rest_after_io[i+1:].rstrip(');').strip()
            if args_part.startswith(','):
                args_part = args_part[1:].strip()
            if args_part:
                return f'    printf("{fmt}\\n", {args_part});'
            return f'    printf("{fmt}\\n");'

        # Strip @require/@ensure annotations
        s = re.sub(r'\s*@\w+\([^)]*\)', '', s)

        # Suppress gcc -Wunused-result warnings on bare fread() calls
        # (void) alone doesn't work with __attribute__((warn_unused_result))
        s = re.sub(r'fread\(([^)]+)\)',
                   r'{ size_t _r = fread(\1); (void)_r; }', s)

        # Everything else: pass through with indent
        return f'    {s}'

    def _tokenize(self, source_code):
        from c3ppc.lexer.lexer import create_c3pp_lexer
        self._lexer = create_c3pp_lexer()
        return self._lexer.tokenize(source_code)

    def _parse_source(self, source_code, tokens):
        parsed = {'module': '', 'imports': [], 'functions': [], 'constants': [],
                  'globals': [], 'classes': [], 'enums': [], 'faults': [], 'typedefs': []}
        lines = source_code.split('\n')
        i = 0
        while i < len(lines):
            s = lines[i].strip()
            if s.startswith('//') or not s: i += 1; continue
            if s.startswith('module '):
                parsed['module'] = s[7:].rstrip(';').strip(); i += 1; continue
            if s.startswith('import '):
                imp = s[7:].rstrip(';').strip()
                parsed['imports'].append(imp); i += 1; continue
            if s.startswith('fault '):
                parsed['faults'].append(s); i += 1; continue
            if s.startswith('enum '):
                b, e = self._collect_block(lines, i); parsed['enums'].append({'code': b}); i = e; continue
            if s.startswith('class ') or s.startswith('struct '):
                b, e = self._collect_block(lines, i); parsed['classes'].append({'code': b}); i = e; continue
            if s.startswith('const '):
                parsed['constants'].append(s); i += 1; continue
            if s.startswith('fn '):
                b, e = self._collect_function(lines, i); parsed['functions'].append({'code': b}); i = e; continue
            if s.startswith('alias '):
                parsed['typedefs'].append(s); i += 1; continue
            if re.match(r'^[\w*\[\]<>?]+\s+\w+(\s*\[.*?\])?\s*[=;(]', s):
                parsed['globals'].append(s); i += 1; continue
            i += 1
        return parsed

    def _collect_block(self, lines, start):
        r = []; d = 0; f = False
        for idx in range(start, len(lines)):
            r.append(lines[idx]); d += _count_braces(lines[idx])
            if d > 0: f = True
            if f and d <= 0: return '\n'.join(r), idx + 1
        return '\n'.join(r), len(lines)

    def _collect_function(self, lines, start):
        r = []; d = 0; f = False
        for idx in range(start, len(lines)):
            r.append(lines[idx]); d += _count_braces(lines[idx])
            if '{' in lines[idx] and '}' in lines[idx] and not f: f = True
            if d > 0: f = True
            if f and d <= 0: return '\n'.join(r), idx + 1
        return '\n'.join(r), len(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="c3ppc - C3++ to x86-64 assembly compiler",
        epilog="Generates x86-64 assembly (.s), assembled with: gcc -o out out.s",
    )
    parser.add_argument("input_file", help="Input C3++ source file")
    parser.add_argument("-o", "--output", help="Output file (.s or .c)")
    parser.add_argument("-v", "--verbose", action="store_true")
    parser.add_argument("--c", action="store_true",
                        help="Generate C code instead of x86-64 assembly")
    parser.add_argument("--version", action="version", version="c3ppc 4.0.0")
    args = parser.parse_args()

    if not os.path.exists(args.input_file):
        print(f"Error: '{args.input_file}' not found", file=sys.stderr); sys.exit(1)
    try:
        with open(args.input_file, 'r') as f: source_code = f.read()
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr); sys.exit(1)

    options = CompilerOptions(input_file=args.input_file, output_file=args.output,
                              verbose=args.verbose, emit_c=getattr(args, 'c', False))
    compiler = C3ppCompiler(options)
    try:
        result = compiler.compile(source_code)
        if result:
            if args.output:
                with open(args.output, 'w') as f: f.write(result)
                if args.verbose: print(f"Written to {args.output}")
            else:
                print(result)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        if args.verbose: import traceback; traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
